spring:
  application:
    name: qr-code-generator-service
  datasource:
    url: jdbc:mysql://localhost:3306/qcg
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true